### ISSUE TITLE
Distance

### ISSUE THREAD

**Issue by Sladamos** [bartekmp/AW_KNN#1]
Issue in [main.cpp](https://github.com/bartekmp/AW_KNN/blob/master/AW_1/main.cpp) in line 34.
There is triple calculation of x distance.
In my opinion it should looks like:
`
dist = sqrt(pow(other.x - this->x, 2) + pow(other.y - this->y, 2) + pow(other.z - this->z, 2));
`
Same problem exists in other mains.

**Comment by bartekmp** [comment]
Thanks for your comment.
This repository was created 7 years ago, while I was still studying at the university, as a result of one of the projects I had back then.
I have no plans in improving anything in that code anymore, I'll leave your issue as a note for anyone interested in using it anyhow in the future.
